package Views;

import java.awt.Color;
import javax.swing.JOptionPane;
import conexiondb.ConexionSQLServer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.*;

/**
 *
 * @author lucia
 */
public class LoginViewEmpleado extends javax.swing.JFrame {
    private String cargo;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginViewEmpleado.class.getName());

    /**
     * Creates new form LoginView
     */
    public LoginViewEmpleado() {
        initComponents();
        
       
    }
  
public boolean verificarCredenciales(String usuario, String contraseña, String tipoUsuario) {
    boolean autenticado = false;
    try {
        Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=BD_TPOO", "lucianoadm", "hilario123");

        String query = "";
        if (tipoUsuario.equals("cliente")) {
            query = "SELECT * FROM CLIENTE WHERE  (usuario = ? OR correo) = ? AND contraseña = ?";
        } else if (tipoUsuario.equals("empleado")) {
            query = "SELECT * FROM EMPLEADO WHERE (usuario = ? OR correo) = ? AND contraseña = ?";
        }

        PreparedStatement stmt = con.prepareStatement(query);
        stmt.setString(1, usuario);
        stmt.setString(2, usuario);
        stmt.setString(3, contraseña);
        ResultSet rs = stmt.executeQuery();

        if (rs.next()) {
            autenticado = true; 
        }
        con.close();
    } catch (SQLException e) {
        System.out.println("Error en la autenticación: " + e.getMessage());
    }
    return autenticado;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        bg = new javax.swing.JPanel();
        imagenLogo = new javax.swing.JLabel();
        imagenFondo = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        lblIniciarSesion = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuarioEmpleado = new javax.swing.JTextField();
        txtContraseñaEmpleado = new javax.swing.JPasswordField();
        imagenLoguin = new javax.swing.JLabel();
        btnEntrarEmpleado = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(153, 255, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bg.setBackground(new java.awt.Color(0, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagenLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/logo.png"))); // NOI18N
        bg.add(imagenLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 210, 220));

        imagenFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/libreria_interior (1).png"))); // NOI18N
        bg.add(imagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 210, 580));

        lblContraseña.setBackground(new java.awt.Color(255, 255, 255));
        lblContraseña.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lblContraseña.setText("CONTRASEÑA");
        bg.add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, -1, -1));

        lblIniciarSesion.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lblIniciarSesion.setText("INICIAR SESIÓN COMO EMPLEADO");
        bg.add(lblIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 430, 40));

        lblUsuario.setBackground(new java.awt.Color(255, 255, 255));
        lblUsuario.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lblUsuario.setText("USUARIO / CORREO");
        bg.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, -1, -1));

        txtUsuarioEmpleado.setForeground(new java.awt.Color(153, 153, 153));
        txtUsuarioEmpleado.setText("Ingrese su nombre de usuario");
        txtUsuarioEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUsuarioEmpleadoMousePressed(evt);
            }
        });
        txtUsuarioEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioEmpleadoActionPerformed(evt);
            }
        });
        bg.add(txtUsuarioEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 300, 30));

        txtContraseñaEmpleado.setForeground(new java.awt.Color(153, 153, 153));
        txtContraseñaEmpleado.setText("********");
        txtContraseñaEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtContraseñaEmpleadoMousePressed(evt);
            }
        });
        bg.add(txtContraseñaEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 300, 30));

        imagenLoguin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/imagenLogueo.png"))); // NOI18N
        bg.add(imagenLoguin, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 100, 110));

        btnEntrarEmpleado.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnEntrarEmpleado.setText("ENTRAR");
        btnEntrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarEmpleadoActionPerformed(evt);
            }
        });
        bg.add(btnEntrarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 120, 50));

        btnAtras.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnAtras.setText("ATRÁS");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        bg.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 150, 30));

        btnSalir.setBackground(new java.awt.Color(51, 255, 255));
        btnSalir.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/icono_X.png"))); // NOI18N
        btnSalir.setBorder(null);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        bg.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioEmpleadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioEmpleadoMousePressed
        if(txtUsuarioEmpleado.getText().equals("Ingrese su nombre de usuario")){
            txtUsuarioEmpleado.setText("");
            txtUsuarioEmpleado.setForeground(Color.black);
        }
        if(String.valueOf(txtContraseñaEmpleado.getPassword()).isEmpty()){   
            txtContraseñaEmpleado.setText("********");
            txtContraseñaEmpleado.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtUsuarioEmpleadoMousePressed

    private void txtContraseñaEmpleadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContraseñaEmpleadoMousePressed
       if(String.valueOf(txtContraseñaEmpleado.getPassword()).equals("********")){
            txtContraseñaEmpleado.setText("");
            txtContraseñaEmpleado.setForeground(Color.black);
       }
       if(txtUsuarioEmpleado.getText().isEmpty()){
            txtUsuarioEmpleado.setText("Ingrese su nombre de usuario");
           txtUsuarioEmpleado.setForeground(Color.gray);
       }
     
    }//GEN-LAST:event_txtContraseñaEmpleadoMousePressed

    private void txtUsuarioEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioEmpleadoActionPerformed

    private void btnEntrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarEmpleadoActionPerformed
   btnEntrarEmpleado.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            String usuario = txtUsuarioEmpleado.getText();
            String contraseña = new String(txtContraseñaEmpleado.getPassword());

            boolean autenticado = ConexionSQLServer.authenticateEmpleado(usuario, contraseña);

            if (autenticado) {
                LoginViewEmpleado.this.setVisible(false); 
                Sistema SistemaFrame = new Sistema(usuario);  
                SistemaFrame.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos.");
            }
        }
    });
    }//GEN-LAST:event_btnEntrarEmpleadoActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        btnAtras.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                LoginViewEmpleado.this.setVisible(false);
                LoginUsuarios loginUsuarios = new LoginUsuarios();
                loginUsuarios.setVisible(true);  
            }
        });
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int respuesta=JOptionPane.showOptionDialog(this,"¿Estas seguro de salir?","Mensaje de Confirmación",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,null,null);
        if(respuesta==0) System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed
    
    public String obtenerCargoEmpleado(String usuario) {
        String cargo = "";
        try {
            Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=BD_TPOO", "lucianoadm", "hilario123");
            String query = "SELECT cargo FROM EMPLEADO WHERE usuario = ?";
            PreparedStatement stmt = con.prepareStatement(query);
            stmt.setString(1, usuario);
            ResultSet rs = stmt.executeQuery();
            if (rs.next()) {
                cargo = rs.getString("cargo");
            }
            con.close();
        } catch (SQLException e) {
            System.out.println("Error al obtener el cargo: " + e.getMessage());
        }
        return cargo;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
      
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnEntrarEmpleado;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel imagenFondo;
    private javax.swing.JLabel imagenLogo;
    private javax.swing.JLabel imagenLoguin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblIniciarSesion;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField txtContraseñaEmpleado;
    private javax.swing.JTextField txtUsuarioEmpleado;
    // End of variables declaration//GEN-END:variables
}
