package Views;

import javax.swing.JOptionPane;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class RegistroView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistroView.class.getName());

    /**
     * Creates new form LoginView
     */
    public RegistroView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        bg = new javax.swing.JPanel();
        imagenLogo = new javax.swing.JLabel();
        imagenFondo = new javax.swing.JLabel();
        imagenLoguin = new javax.swing.JLabel();
        btnRegistroCliente = new javax.swing.JButton();
        btnRegistroEmpleado = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(153, 255, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bg.setBackground(new java.awt.Color(0, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagenLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/logo.png"))); // NOI18N
        bg.add(imagenLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 210, 220));

        imagenFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/libreria_interior (1).png"))); // NOI18N
        bg.add(imagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 210, 580));

        imagenLoguin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/imagenLogueo.png"))); // NOI18N
        bg.add(imagenLoguin, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 100, 110));

        btnRegistroCliente.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnRegistroCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/registrarse (1).png"))); // NOI18N
        btnRegistroCliente.setText("REGISTRAR CLIENTE");
        btnRegistroCliente.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnRegistroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroClienteActionPerformed(evt);
            }
        });
        bg.add(btnRegistroCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 270, 80));

        btnRegistroEmpleado.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnRegistroEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/registrarse (1).png"))); // NOI18N
        btnRegistroEmpleado.setText("REGISTRAR EMPLEADO");
        btnRegistroEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnRegistroEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroEmpleadoActionPerformed(evt);
            }
        });
        bg.add(btnRegistroEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 290, 80));

        jPasswordField1.setText("jPasswordField1");
        bg.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 90, 30));

        jLabel1.setText("Codigo de Seguridad (para empleados):");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, -1, -1));

        btnAtras.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnAtras.setText("ATRÁS");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        bg.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 150, 30));

        btnSalir.setBackground(new java.awt.Color(51, 255, 255));
        btnSalir.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/icono_X.png"))); // NOI18N
        btnSalir.setBorder(null);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        bg.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroClienteActionPerformed
        btnRegistroCliente.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            RegistroClienteView registroFrame = new RegistroClienteView();
            registroFrame.setVisible(true);
            setVisible(false);
        }
    });
    }//GEN-LAST:event_btnRegistroClienteActionPerformed

    private void btnRegistroEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroEmpleadoActionPerformed
        btnRegistroEmpleado.addActionListener(new ActionListener() {
        @Override
        
        public void actionPerformed(ActionEvent e) {
            String codigoIngresado = jPasswordField1.getText();
            String codigoValido = "12345";
            if (codigoIngresado.equals(codigoValido)) {
                RegistroEmpleadoView registroFrame = new RegistroEmpleadoView();
                registroFrame.setVisible(true);
                setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, "Código incorrecto. Por favor ingresa el código válido.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    });
    }//GEN-LAST:event_btnRegistroEmpleadoActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        btnAtras.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                LoginUsuarios loginUsuarios = new LoginUsuarios();
                loginUsuarios.setVisible(true);
            }
        });
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int respuesta=JOptionPane.showOptionDialog(this,"¿Estas seguro de salir?","Mensaje de Confirmación",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,null,null);
        if(respuesta==0) System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnRegistroCliente;
    private javax.swing.JButton btnRegistroEmpleado;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel imagenFondo;
    private javax.swing.JLabel imagenLogo;
    private javax.swing.JLabel imagenLoguin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
